//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMeiko.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA0006
    {
        public int RKEY { get; set; }
        public string WORK_ORDER_NUMBER { get; set; }
        public Nullable<int> INVENTORY_PTR { get; set; }
        public Nullable<int> CUST_PART_PTR { get; set; }
        public Nullable<int> ROOT_PTR { get; set; }
        public Nullable<int> WHOUSE_PTR { get; set; }
        public Nullable<int> ENGG_RTE_PTR { get; set; }
        public Nullable<int> PROD_RTE_PTR { get; set; }
        public Nullable<int> CSI_USER_PTR { get; set; }
        public Nullable<int> EMPLOYEE_PTR { get; set; }
        public Nullable<int> BOM_PTR { get; set; }
        public Nullable<int> SUB_LEVELS { get; set; }
        public string PRIORITY_CODE { get; set; }
        public Nullable<int> ENGG_STATUS { get; set; }
        public Nullable<int> PROD_STATUS { get; set; }
        public Nullable<int> ENGG_PROD_FLAG { get; set; }
        public string ENGG_RTE_MOD_FLAG { get; set; }
        public string PROD_RTE_MOD_FLAG { get; set; }
        public string BOM_MOD_FLAG { get; set; }
        public Nullable<decimal> QUAN_SCH { get; set; }
        public Nullable<decimal> QUAN_REJ { get; set; }
        public Nullable<decimal> QUAN_PROD { get; set; }
        public Nullable<System.DateTime> ENT_DATE { get; set; }
        public Nullable<int> ENT_TIME { get; set; }
        public Nullable<System.DateTime> SCH_COMPL_DATE { get; set; }
        public Nullable<System.DateTime> PROJ_START_DATE { get; set; }
        public Nullable<System.DateTime> PROJ_COMPL_DATE { get; set; }
        public Nullable<System.DateTime> CANCEL_HOLD_DATE { get; set; }
        public Nullable<System.DateTime> ACT_COMPL_DATE { get; set; }
        public string CUST_PART_REV_NO { get; set; }
        public string BOM_REV_NO { get; set; }
        public Nullable<int> TAG_PTR { get; set; }
        public Nullable<System.DateTime> DT_PTRAV_PRN { get; set; }
        public Nullable<System.DateTime> DT_ETRAV_PRN { get; set; }
        public Nullable<decimal> SCRAP_RATE { get; set; }
        public Nullable<decimal> QUAN_BAL { get; set; }
        public string BASE_WO { get; set; }
        public Nullable<int> PARENT_PTR { get; set; }
        public Nullable<int> RMA_PTR { get; set; }
        public string JOB_COST_FLAG { get; set; }
        public Nullable<int> LOCATION_PTR { get; set; }
        public Nullable<decimal> DIRECT_COST { get; set; }
        public Nullable<decimal> PARTS_PER_PANEL { get; set; }
        public Nullable<decimal> PRODUCTION_COST { get; set; }
        public Nullable<decimal> MATERIAL_COST { get; set; }
        public Nullable<decimal> OVERHEAD_COST { get; set; }
        public Nullable<int> EDITED_BY { get; set; }
        public Nullable<decimal> PLANNED_QTY { get; set; }
        public Nullable<System.DateTime> RELEASE_DATE { get; set; }
        public Nullable<int> TRAV_PRINTED_BY_PTR { get; set; }
        public Nullable<int> LOT_NUMBER_COUNT { get; set; }
        public Nullable<int> HOLD_STEP_NO { get; set; }
        public string HARD_LINK_TO_PARENT { get; set; }
        public string ANALYSIS_CODE_1 { get; set; }
        public string ANALYSIS_CODE_2 { get; set; }
        public string ANALYSIS_CODE_3 { get; set; }
        public string ANALYSIS_CODE_4 { get; set; }
        public string ANALYSIS_CODE_5 { get; set; }
        public string DATE_CODE { get; set; }
        public Nullable<decimal> QUAN_SCH_PANELS { get; set; }
        public Nullable<decimal> QUAN_REJ_PANELS { get; set; }
        public Nullable<decimal> QUAN_PROD_PANELS { get; set; }
        public Nullable<decimal> QUAN_BAL_PANELS { get; set; }
        public Nullable<decimal> XOUT_UNIT_PTR { get; set; }
        public Nullable<decimal> PARTS_PER_XOUT { get; set; }
        public Nullable<decimal> QUAN_SCH_XOUT { get; set; }
        public Nullable<decimal> QUAN_REJ_XOUT { get; set; }
        public Nullable<decimal> QUAN_PROD_XOUT { get; set; }
        public Nullable<decimal> QUAN_BAL_XOUT { get; set; }
    }
}
