//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMeiko.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA0038
    {
        public int RKEY { get; set; }
        public Nullable<int> TTYPE { get; set; }
        public Nullable<int> SOURCE_PTR { get; set; }
        public Nullable<int> DEPT_PTR { get; set; }
        public Nullable<int> DEF_ROUT_INST_1_PTR { get; set; }
        public Nullable<int> DEF_ROUT_INST_2_PTR { get; set; }
        public Nullable<int> DEF_ROUT_INST_3_PTR { get; set; }
        public Nullable<int> DEF_ROUT_INST_4_PTR { get; set; }
        public Nullable<int> DEF_ROUT_INST_5_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_1_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_2_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_3_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_4_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_5_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_6_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_7_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_8_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_9_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_10_PTR { get; set; }
        public string PARAMETER_1 { get; set; }
        public string PARAMETER_2 { get; set; }
        public string PARAMETER_3 { get; set; }
        public string PARAMETER_4 { get; set; }
        public string PARAMETER_5 { get; set; }
        public string PARAMETER_6 { get; set; }
        public string PARAMETER_7 { get; set; }
        public string PARAMETER_8 { get; set; }
        public string PARAMETER_9 { get; set; }
        public string PARAMETER_10 { get; set; }
        public Nullable<int> SETUP_TIME { get; set; }
        public Nullable<int> QUEUE_TIME { get; set; }
        public Nullable<int> PROCESS_TIME { get; set; }
        public Nullable<decimal> PERCENT_COMPLETE { get; set; }
        public Nullable<int> STEP_NUMBER { get; set; }
        public Nullable<decimal> UNIT_VALUE { get; set; }
        public string UNIT_FLAG { get; set; }
        public Nullable<decimal> YIELD { get; set; }
        public string STEP_HOLD { get; set; }
        public Nullable<int> WIP_APPROVAL_FLAG { get; set; }
        public string PROCESS_NAME { get; set; }
        public byte[] CIMNET_KEY { get; set; }
    }
}
