//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMeiko.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA0050
    {
        public int RKEY { get; set; }
        public string CUSTOMER_PART_NUMBER { get; set; }
        public string CUSTOMER_PART_DESC { get; set; }
        public string CP_REV { get; set; }
        public Nullable<decimal> QTY_SCH { get; set; }
        public Nullable<decimal> QTY_REJ { get; set; }
        public Nullable<decimal> QTY_ON_HAND { get; set; }
        public Nullable<decimal> QTY_ALLOC { get; set; }
        public Nullable<decimal> EST_SCRAP { get; set; }
        public Nullable<int> ENGG_ROUTE_PTR { get; set; }
        public Nullable<int> PROD_ROUTE_PTR { get; set; }
        public int CUSTOMER_PTR { get; set; }
        public Nullable<int> BOM_PTR { get; set; }
        public Nullable<int> PROD_CODE_PTR { get; set; }
        public string ENGG_ROUTE_MOD_FLAG { get; set; }
        public string PROD_ROUTE_MOD_FLAG { get; set; }
        public Nullable<int> MFG_LEAD_TIME { get; set; }
        public Nullable<int> ACTIVE_S_ORDERS { get; set; }
        public Nullable<int> ACTIVE_W_ORDERS { get; set; }
        public Nullable<int> UNPLANNED_REL_S { get; set; }
        public Nullable<int> PLANNED_REL_S { get; set; }
        public Nullable<int> FIRM_REL_S { get; set; }
        public Nullable<int> SHELF_LIFE { get; set; }
        public Nullable<System.DateTime> LAST_SO_DATE { get; set; }
        public Nullable<int> OPT_LOT_SIZE { get; set; }
        public Nullable<decimal> FIXED_SCRAP_RATE { get; set; }
        public string CATALOG_NUMBER { get; set; }
        public Nullable<decimal> STANDARD_COST { get; set; }
        public Nullable<decimal> STANDARD_MATERIAL { get; set; }
        public Nullable<decimal> STANDARD_OVERHEAD { get; set; }
        public Nullable<int> INTERNAL_ECN_COUNTER { get; set; }
        public Nullable<int> EXTERNAL_ECN_COUNTER { get; set; }
        public Nullable<int> GENERIC_BOM_POINTER { get; set; }
        public Nullable<decimal> CURRENT_ACT_ACTIVITY { get; set; }
        public Nullable<decimal> CURRENT_ACT_MATERIAL { get; set; }
        public Nullable<System.DateTime> LAST_CURNT_COST_UPDT { get; set; }
        public Nullable<System.DateTime> LAST_STD_COST_UPDT { get; set; }
        public string ALLOW_EDIT_FLAG { get; set; }
        public Nullable<decimal> REPORT_UNIT_VALUE1 { get; set; }
        public Nullable<decimal> REPORT_UNIT_VALUE2 { get; set; }
        public Nullable<decimal> REPORT_UNIT_VALUE3 { get; set; }
        public Nullable<int> SALES_ORDER_UNIT_PTR { get; set; }
        public Nullable<decimal> SALES_ORDER_UNIT_VAL { get; set; }
        public Nullable<System.DateTime> ON_HOLD_DATE { get; set; }
        public Nullable<int> ON_HOLD_BY_PTR { get; set; }
        public Nullable<int> RELEASE_OPT_LOT_SIZE { get; set; }
        public Nullable<decimal> SET_UP_COST { get; set; }
        public Nullable<decimal> PROCESS_COST { get; set; }
        public Nullable<decimal> INDIRECT_MATERIAL1 { get; set; }
        public Nullable<decimal> INDIRECT_MATERIAL2 { get; set; }
        public Nullable<decimal> DIRECT_MATERIAL { get; set; }
        public Nullable<decimal> OVER_HEAD { get; set; }
        public Nullable<int> ONHOLD_PLANNING_FLAG { get; set; }
        public Nullable<int> ONHOLD_RELEASE_FLAG { get; set; }
        public Nullable<int> ONHOLD_SALES_FLAG { get; set; }
        public Nullable<System.DateTime> CUSTPART_ENT_DATE { get; set; }
        public Nullable<int> LAST_MODIFIED_BY_PTR { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<int> AUTO_PLANNING_FLAG { get; set; }
        public Nullable<int> AUTO_RELEASE_FLAG { get; set; }
        public Nullable<decimal> CUR_MONTH_OPEN_BAL { get; set; }
        public string ANALYSIS_CODE_1 { get; set; }
        public string ANALYSIS_CODE_2 { get; set; }
        public string ANALYSIS_CODE_3 { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public Nullable<int> CONSUME_FORECASTS { get; set; }
        public Nullable<int> BACKWARD_DAYS { get; set; }
        public Nullable<int> FORWARD_DAYS { get; set; }
        public Nullable<int> PLANNING_HORIZON { get; set; }
        public Nullable<int> RAW_HORIZON { get; set; }
        public Nullable<int> VISIBILITY_HORIZON { get; set; }
        public Nullable<int> DAYS_EARLY_SCHEDULE { get; set; }
        public Nullable<int> LOT_NUMBER_COUNT { get; set; }
        public Nullable<int> APPLY_IN_TRANSIT { get; set; }
        public Nullable<int> DO_SMOOTHING { get; set; }
        public Nullable<int> SMOOTHING_THRESHOLD { get; set; }
        public string ANALYSIS_CODE_4 { get; set; }
        public string ANALYSIS_CODE_5 { get; set; }
        public Nullable<int> PRODUCTION_PART_PTR { get; set; }
        public string PLAN_INNER_LAYER { get; set; }
        public Nullable<decimal> LAST_SO_PRICE { get; set; }
        public Nullable<int> PBS_PART { get; set; }
        public Nullable<int> LAST_MODIFIED_TIME { get; set; }
        public Nullable<decimal> MIN_STOCK { get; set; }
        public byte[] CIMNET_KEY { get; set; }
        public string LONG_CUSTOMER_PART_NUMBER { get; set; }
        public string LONG_CUSTOMER_PART_DESC { get; set; }
        public string DATE_CODE_FLAG { get; set; }
    }
}
