//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMeiko.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA0034
    {
        public int RKEY { get; set; }
        public string DEPT_CODE { get; set; }
        public string TTYPE { get; set; }
        public string DEPT_NAME { get; set; }
        public Nullable<int> SUPERVISOR_PTR { get; set; }
        public Nullable<int> UNIT_PTR { get; set; }
        public Nullable<int> DEPT_PTR { get; set; }
        public Nullable<int> GROUP_PTR { get; set; }
        public Nullable<int> CAPACITY { get; set; }
        public Nullable<int> SHIFT_1_START_TIME { get; set; }
        public Nullable<int> SHIFT_2_START_TIME { get; set; }
        public Nullable<int> SHIFT_3_START_TIME { get; set; }
        public Nullable<int> SHIFT_1_STOP_TIME { get; set; }
        public Nullable<int> SHIFT_2_STOP_TIME { get; set; }
        public Nullable<int> SHIFT_3_STOP_TIME { get; set; }
        public Nullable<int> DEF_SETUP_TIME { get; set; }
        public Nullable<int> DEF_QUEUE_TIME { get; set; }
        public Nullable<int> DEF_PROCESS_TIME { get; set; }
        public Nullable<int> DEF_ROUT_INST_1_PTR { get; set; }
        public Nullable<int> DEF_ROUT_INST_2_PTR { get; set; }
        public Nullable<int> DEF_ROUT_INST_3_PTR { get; set; }
        public Nullable<int> DEF_ROUT_INST_4_PTR { get; set; }
        public Nullable<int> DEF_ROUT_INST_5_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_1_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_2_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_3_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_4_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_5_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_6_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_7_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_8_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_9_PTR { get; set; }
        public Nullable<int> DEF_ROUT_PARA_10_PTR { get; set; }
        public string PARAMETER_1 { get; set; }
        public string PARAMETER_2 { get; set; }
        public string PARAMETER_3 { get; set; }
        public string PARAMETER_4 { get; set; }
        public string PARAMETER_5 { get; set; }
        public string PARAMETER_6 { get; set; }
        public string PARAMETER_7 { get; set; }
        public string PARAMETER_8 { get; set; }
        public string PARAMETER_9 { get; set; }
        public string PARAMETER_10 { get; set; }
        public Nullable<decimal> LABOR_RATE_1 { get; set; }
        public Nullable<decimal> LABOR_RATE_2 { get; set; }
        public Nullable<decimal> LABOR_RATE_3 { get; set; }
        public Nullable<decimal> LABOR_OVERHEAD { get; set; }
        public Nullable<int> COST_UNIT_PTR { get; set; }
        public Nullable<decimal> COST_DRIVER { get; set; }
        public Nullable<decimal> FIXED_BURDEN { get; set; }
        public Nullable<decimal> VARIABLE_BURDEN { get; set; }
        public string SCHEDULE_FLAG { get; set; }
        public string REMOTE_T_PUT_FLAG { get; set; }
        public Nullable<int> THRESHOLD_UNIT_PTR { get; set; }
        public Nullable<decimal> MINIMUM_COST { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public Nullable<int> WORK_CENTER_TYPE { get; set; }
        public Nullable<int> SET_UP_TYPE { get; set; }
        public string BARCODE_ENTRY_FLAG { get; set; }
        public Nullable<decimal> PRODUCTION_RATE { get; set; }
        public Nullable<int> WAREHOUSE_PTR { get; set; }
        public Nullable<int> THRESHOLD_AMOUNT { get; set; }
        public string FACILITY_CODE { get; set; }
        public string ALLOW_SPLIT_LOTS { get; set; }
        public Nullable<decimal> ACTUAL_ACTIVITY_RATE { get; set; }
        public Nullable<decimal> DRIVER_BREAKDOWN1 { get; set; }
        public Nullable<decimal> DRIVER_BREAKDOWN2 { get; set; }
        public Nullable<decimal> DRIVER_BREAKDOWN3 { get; set; }
        public string ALLOW_OVERPRODUCTION { get; set; }
        public Nullable<decimal> SET_UP_COST { get; set; }
        public Nullable<decimal> PROCESS_COST { get; set; }
        public Nullable<decimal> DIRECT_MATERIAL { get; set; }
        public Nullable<decimal> INDIRECT_MATERIAL_1 { get; set; }
        public Nullable<decimal> INDIRECT_MATERIAL_2 { get; set; }
        public Nullable<decimal> OVERHEAD { get; set; }
        public string CONSIGNMENT_TYPE { get; set; }
        public Nullable<int> TRANSFER_RESOURCE { get; set; }
        public Nullable<int> DOCK_RESOURCE { get; set; }
        public Nullable<int> PRINTING_RESOURCE { get; set; }
        public Nullable<int> FACILITY_PTR { get; set; }
        public Nullable<int> BCODE_UNIT_PTR { get; set; }
        public Nullable<int> USE_DEFECT_UNIT { get; set; }
        public string STEP_HOLD { get; set; }
        public Nullable<int> PROCESS_UNIT_PTR { get; set; }
        public Nullable<int> DM_UNIT_PTR { get; set; }
        public Nullable<int> IDM_1_UNIT_PTR { get; set; }
        public Nullable<int> IDM_2_UNIT_PTR { get; set; }
        public Nullable<int> OVHD_UNIT_PTR { get; set; }
        public string ANALYSIS_CODE_1 { get; set; }
        public string ANALYSIS_CODE_2 { get; set; }
        public string ANALYSIS_CODE_3 { get; set; }
        public string ANALYSIS_CODE_4 { get; set; }
        public string ANALYSIS_CODE_5 { get; set; }
        public Nullable<int> SUBCON_TYPE_PTR { get; set; }
        public Nullable<int> WIP_APPROVAL_FLAG { get; set; }
        public string PROCESS_NAME { get; set; }
        public Nullable<bool> ACTIVE_FLAG { get; set; }
        public Nullable<int> XOUT_WC { get; set; }
    }
}
