//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMeiko.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DATA0006> DATA0006 { get; set; }
        public DbSet<DATA0035> DATA0035 { get; set; }
        public DbSet<DATA0038> DATA0038 { get; set; }
        public DbSet<DATA0050> DATA0050 { get; set; }
        public DbSet<DATA0034> DATA0034 { get; set; }
    }
}
