export class Dodungcanhan{
      Dodungid:string
      Phongid:string
      Tenphong:string
      Masododung:string
      Tendodung:string
      Soluongtong:number
      Soluongdadung:number
      Soluongchuadung:number
      Soluongbaophe:number
      Phanloai:boolean
      Trigia:string
      Ghichu:string
      Trangthai:boolean
      Thutu:number
      Ngaycapnhap:string
      Nguoitaoid:string
      Nguoitao:string
      Nhanviendangkyid:string
      Soluongcapphat:number
      edittable:boolean=false
}