//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flux
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flux()
        {
            this.QuyTrinhs = new HashSet<QuyTrinh>();
        }
    
        public System.Guid Flux_id { get; set; }
        public string Thoigiantao { get; set; }
        public string Thoigianhoanthanh { get; set; }
        public string Mahang { get; set; }
        public string Malot { get; set; }
        public string Doday { get; set; }
        public int Soluong { get; set; }
        public float Dodaytruoc { get; set; }
        public float Dodaysau { get; set; }
        public string Xacnhantaixuly { get; set; }
        public string Ghichu { get; set; }
        public int trangthai { get; set; }
        public int Thutu { get; set; }
        public string GroupFlux { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyTrinh> QuyTrinhs { get; set; }
    }
}
