//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppMeikoEntities : DbContext
    {
        public AppMeikoEntities()
            : base("name=AppMeikoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flux> Fluxes { get; set; }
        public virtual DbSet<NhomKy> NhomKies { get; set; }
        public virtual DbSet<QuyTrinh> QuyTrinhs { get; set; }
        public virtual DbSet<UserNhomKy> UserNhomKies { get; set; }
    }
}
